---
- name: Starting to install chrome
  include_tasks: chrome.yml

- name: Starting to install sublime
  include_tasks: sublime.yml

- name: Install general package
  apt:
    name: "{{ item }}"
  with_items:
    - vim
    - htop