---

- name: Install key
  shell: "wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -"

- name: Add apt repository
  shell: "echo 'deb https://download.sublimetext.com/ apt/stable/' | sudo tee /etc/apt/sources.list.d/sublime-text.list"

- name: Install Sublime
  apt:
    name: sublime-text
    cache_valid_time: 1800
    update_cache: yes
  become: yes


