---

- name: Install sublime key
  shell: "wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -"

- name: Add sublime apt repository
  shell: "echo 'deb https://download.sublimetext.com/ apt/stable/' | sudo tee /etc/apt/sources.list.d/sublime-text.list"

- name: get-update
  shell: "apt-get update"
  become: yes
  ignore_errors: yes

- name: Install Sublime text 3
  apt:
    name: sublime-text
  become: yes

- name: Create configure directory
  file:
    path: ~/.config/sublime-text-3/Packages/User/
    state: directory

- name: Configure Sublime text 3
  copy:
    src: files/sublime/Preferences.sublime-settings
    dest: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
