---
- name: Copy vscode 
  copy:
    src: files/vscode/vscode_1.30amd64.deb
    dest: /tmp/vscode_1.30amd64.deb
  become: yes

- name: Install Visual Studio Code
  apt:
    deb: /tmp/vscode_1.30amd64.deb
  become: yes

- name: Install theme
  shell: git clone https://github.com/equinusocio/vsc-material-theme.git ~/.vscode/extensions/Equinusocio.vsc-material-theme
