---

- name: Copy vscode 
  copy:
    src: files/vscode/vscode_1.30amd64.deb
    dest: /opt/vscode_1.30amd64.deb
  become: yes

- name: Install Visual Studio Code
  shell: "apt install /opt/vscode_1.30amd64.deb"
  become: yes