---
- hosts: localhost
  connection: local

  vars:
    user: niklas
    git_email: niklas.haetty@gmail.com
    git_name: "Niklas Hätty"

  tasks:
    - include_role: 
        name: utils
      tags:
        - utils

    - include_role: 
        name: appearance
      tags:
        - appearance

    - include_role:
        name: programs
      tags:
        - programs

# To run everything:
# ansible-playbook start.yml --ask-become-pass

# To skip e.g. programs:
# ansible-playbook start.yml --ask-become-pass --skip-tags "programs"

# To only run e.g. programs and utils
# ansible-playbook start.yml --ask-become-pass --tags "programs, utils"