---
- hosts: localhost
  connection: local

  vars:
    user: niklas

  tasks:
    - include_role: 
        name: utils
    - include_role: 
        name: appearance
    - include_role:
        name: programs

# ansible-playbook start.yml --extra-vars "ansible_become_pass=qwertyui"