---
- name: Install easy_install
  apt:
    name: ['python-setuptools', 'python-dev', 'build-essential']
  become: yes

- name: Install general packages
  apt:
    name: "{{ item }}"
  with_items:
    - vim
    - htop
    - screenfetch
    - python-pip
    - python-psutil
  become: yes