---

- name: Set wallpaper
  shell: "xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/workspace0/last-image --set {{ install_dir }}/wallpaper.png"

- name: Remove default icons
  shell: "xfconf-query --channel xfce4-desktop --property /desktop-icons/file-icons/show-{{item}} --set false"
  with_items:
    - home
    - filesystem
    - trash
    - removable
