---
- apt_repository:
    repo: ppa:papirus/papirus
    state: present
    update_cache: yes
  ignore_errors: yes

- name: Install papirus-icon-theme
  apt:
    name: papirus-icon-theme
  become: yes

- name: Set icons to papirus-icon-theme
  shell: "xfconf-query --channel xsettings --property /Net/IconThemeName --set papirus-icon-theme"

