---
- name: Starting ppa.yml
  include_tasks: ppa.yml

- name: Update apt
  become: yes
  apt:
    cache_valid_time: 1800
    update_cache: yes
  ignore_errors: yes

- name: Starting desktop.yml
  include_tasks: desktop.yml

- name: Starting theme.yml
  include_tasks: theme.yml

- name: Starting icons.yml
  include_tasks: icons.yml

- name: Starting terminal.yml
  include_tasks: terminal.yml

- name: Starting panel.yml
  include_tasks: panel.yml

- name: Starting fonts.yml
  include_tasks: fonts.yml