---
- name: Import panel confs
  shell: xfpanel-switch load {{ install_dir }}/panel/panel.tar.bz2

- name: Copy panel icon
  copy:
    src: "{{ install_dir }}/ao-app-tray.svg"
    dest: "/usr/share/icons/ao-app-tray.svg"
  become: yes