---
- name: Set panel opacity to 50
  shell: "xfconf-query --channel xfce4-panel --property /panels/panel-0/background-alpha --set 50"

- name: Copy menu logo to icon dir
  copy:
    src: files/ao-app-tray.svg
    dest: /usr/share/icons/ao-app-tray.svg
  become: yes

- name: Unlock panel
  shell: "xfconf-query --channel xfce4-panel --property /panels/panel-0/position -s p=8;x=400;y=970"
  become: yes

- name: Set panel size
  shell: "xfconf-query --channel xfce4-panel --property /panels/panel-0/size -s 34"
  become: yes

- name: Reload panel
  shell: "xfce4-panel -r"