---
- name: Bind terminal to Insert
  shell: "xfconf-query --channel xfce4-keyboard-shortcuts --create --type string --property /commands/custom/Insert --set 'xfce4-terminal --drop-down'"

- name: Make ~/usr/share/xfce4/terminal/colorschemes/
  file:
    path: ~/usr/share/xfce4/terminal/colorschemes/
    state: directory

- name: Copy terminal theme
  copy:
    src: "{{ install_dir }}/terminal/nord.theme"
    dest: ~/usr/share/xfce4/terminal/colorschemes/nord.theme

- name: Switch terminal theme 1
  shell: grep -Fxvf <(cat /usr/share/xfce4/terminal/colorschemes/*.theme) ~/.config/xfce4/terminal/terminalrc > ~/.config/xfce4/terminal/.terminalrc.tmp

- name: Switch terminal theme 2
  shell: grep -v -e Name -e Scheme "/usr/share/xfce4/terminal/colorschemes/nord.theme" >> ~/.config/xfce4/terminal/.terminalrc.tmp

- name: Switch terminal theme 3
  shell: mv ~/.config/xfce4/terminal/.terminalrc.tmp ~/.config/xfce4/terminal/terminalrc