---
- name: Make ~/usr/share/xfce4/terminal/colorschemes/
  file:
    path: ~/usr/share/xfce4/terminal/colorschemes/
    state: directory

- name: Copy terminal theme
  copy:
    src: "{{ install_dir }}/terminal/nord.theme"
    dest: ~/usr/share/xfce4/terminal/colorschemes/nord.theme

- name: Copy terminal settings and switch theme
  copy:
    src: "{{ install_dir }}/terminal/terminalrc"
    dest: "~/.config/xfce4/terminal/terminalrc"