---
- name: Make ~/.themes/
  file:
    path: ~/.themes/
    state: directory

- name: Extract victory-gtk-theme-18.07.tar.gz theme to ~/.themes/
  unarchive:
    src: "{{ install_dir}}/theme/victory-gtk-theme-18.07.tar.gz"
    dest: ~/.themes/

- name: Set theme to victory-gtk-theme-18
  shell: "xfconf-query --channel xsettings --property /Net/ThemeName --set victory-gtk-theme-18.07"

